import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/coverage/**',
      'unity/**',
      // Generated by Next.js on build; not ours to lint.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      eqeqeq: ['error', 'always'],
      'no-console': 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // CLAUDE.md — "Keep game rules out of UI components." and
  // "Keep realtime transport separate from game rules."
  //
  // packages/game-rules must stay pure and testable: no I/O, no transport, no
  // framework. These bans are the mechanical enforcement of that boundary.
  // ---------------------------------------------------------------------------
  {
    files: ['packages/game-rules/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'node:http', message: 'game-rules must stay pure. No I/O.' },
            { name: 'node:fs', message: 'game-rules must stay pure. No I/O.' },
            { name: 'node:net', message: 'game-rules must stay pure. No I/O.' },
            { name: 'react', message: 'game-rules must not depend on UI.' },
            { name: 'next', message: 'game-rules must not depend on UI.' },
            {
              name: 'socket.io',
              message: 'Transport must sit behind an adapter. See ARCHITECTURE.md §7.',
            },
            {
              name: 'ws',
              message: 'Transport must sit behind an adapter. See ARCHITECTURE.md §7.',
            },
          ],
          patterns: ['socket.io*', 'ws/*'],
        },
      ],

      // CLAUDE.md — "Use a deterministic/fake clock for timing tests."
      // The server owns time; rule functions must receive it, never read it.
      'no-restricted-globals': [
        'error',
        {
          name: 'Date',
          message:
            'Do not read wall-clock time inside game rules. Accept a Clock parameter instead. See packages/game-rules/src/clock.ts',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "MemberExpression[object.name='Date'][property.name='now']",
          message:
            'Do not read wall-clock time inside game rules. Accept a Clock parameter instead. See packages/game-rules/src/clock.ts',
        },
        {
          selector: "CallExpression[callee.name='setTimeout']",
          message: 'Game rules must not schedule real timers. The server timer service owns this.',
        },
        {
          selector: "CallExpression[callee.name='setInterval']",
          message: 'Game rules must not schedule real timers. The server timer service owns this.',
        },
      ],
    },
  },

  // The clock implementation itself is the one place allowed to read real time.
  {
    files: ['packages/game-rules/src/clock.ts'],
    rules: {
      'no-restricted-globals': 'off',
      'no-restricted-syntax': 'off',
    },
  },

  {
    files: ['**/*.test.ts', '**/*.spec.ts'],
    rules: {
      'no-restricted-globals': 'off',
      'no-restricted-syntax': 'off',
    },
  },
);
